/*
* ============================================================================
*  Name     : CMMS_ItView from MMS_ItView.h
*  Part of  : MMS_It
*  Created  : 29/9/2003 by Makidis Michael
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Copyright: Makidis Michael 2003-2005
* ============================================================================
*/

// INCLUDE FILES
#include  <aknviewappui.h>
#include  <avkon.hrh>
#include <MMS_IT.RSG>
#include  "MMS_ItView.h"
#include  "MMS_It.hrh"
#include  "MMS_ItContainer.h" 

// ================= MEMBER FUNCTIONS =======================

CMMS_ItView::CMMS_ItView(CMMS_ItAppUi* aUI)
: iUI(aUI)
{}

// ---------------------------------------------------------
// CMMS_ItView::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
void CMMS_ItView::ConstructL()
    {
    BaseConstructL( R_MMS_IT_VIEW1 );
    }

// ---------------------------------------------------------
// CMMS_ItView::~CMMS_ItView()
// ?implementation_description
// ---------------------------------------------------------
//
CMMS_ItView::~CMMS_ItView()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
    }

// ---------------------------------------------------------
// TUid CMMS_ItView::Id()
// ?implementation_description
// ---------------------------------------------------------
//
TUid CMMS_ItView::Id() const
    {
    return KViewId;
    }

// ---------------------------------------------------------
// CMMS_ItView::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CMMS_ItView::HandleCommandL(TInt aCommand)
    {   
		AppUi()->HandleCommandL( aCommand );
    }

// ---------------------------------------------------------
// CMMS_ItView::HandleClientRectChange()
// ---------------------------------------------------------
//
void CMMS_ItView::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CMMS_ItView::DoActivateL(...)
// ?implementation_description
// ---------------------------------------------------------
//
void CMMS_ItView::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CMMS_ItContainer(iUI);
        iContainer->SetMopParent(this);
        iContainer->ConstructL( ClientRect() );
        AppUi()->AddToStackL( *this, iContainer );
        }
	iUI->ShowDefaultNaviPaneL();
   }

// ---------------------------------------------------------
// CMMS_ItView::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CMMS_ItView::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

// End of File

