/*
* ============================================================================
*  Name     : CMMS_ItView2 from MMS_ItView2.h
*  Part of  : MMS_It
*  Created  : 21/11/2004 by 
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Copyright: Makidis Michael 2003-2005
* ============================================================================
*/

// INCLUDE FILES
#include  <aknviewappui.h>
#include  <avkon.hrh>
#include  <MMS_It.rsg>
#include  "MMS_ItView2.h"
#include  "MMS_ItContainer2.h"
#include "mms_it.hrh"

#include "MMS_ItDocument.h"
#include "MMS_ItAppUi.h"

#include <stringloader.h>  // for StringLoader
#include <AknQueryDialog.h>  // for queries
#include <aknnotewrappers.h> // for notes

// ================= MEMBER FUNCTIONS =======================

CMMS_ItView2::CMMS_ItView2(CMMS_ItDocument* aDocument, CMMS_ItAppUi* aUI)
:	iDocument(aDocument), iUI(aUI)
{
}

// ---------------------------------------------------------
// CMMS_ItView2::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
void CMMS_ItView2::ConstructL()
    {
    BaseConstructL( R_MMS_IT_VIEW2 );
    }

// ---------------------------------------------------------
// CMMS_ItView2::~CMMS_ItView2()
// ?implementation_description
// ---------------------------------------------------------
//
CMMS_ItView2::~CMMS_ItView2()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
    }

// ---------------------------------------------------------
// TUid CMMS_ItView2::Id()
// ?implementation_description
// ---------------------------------------------------------
//
TUid CMMS_ItView2::Id() const
    {
    return KView2Id;
    }

// ---------------------------------------------------------
// CMMS_ItView2::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CMMS_ItView2::HandleCommandL(TInt aCommand)
    {   
    switch ( aCommand )
        {
        case ESend:
            {
            if(iContainer) iContainer->SaveMessageText();
			AppUi()->HandleCommandL( aCommand );
            break;
            }
		case EEditSubject:
			{
			if(iContainer) iContainer->SaveMessageText();
			TBuf<100> subject;
			if(iDocument->SubjectSet()) subject = iDocument->GetSubject();
			// ask for the subject
			CAknTextQueryDialog* subjectDialog = CAknTextQueryDialog::NewL(subject, CAknQueryDialog::ENoTone);
			if (subjectDialog->ExecuteLD(R_MMS_IT_SUBJECT_DIALOG))
			{
				iDocument->SetSubject(subject);
				UpdateContainer();
			}
			break;
			}
		case ESetSMILRoot:
			{
			if(iContainer) iContainer->SaveMessageText();
			TFileName filename;
			// ask for the subject
			CAknTextQueryDialog* smilDialog = CAknTextQueryDialog::NewL(filename, CAknQueryDialog::ENoTone);
			if (smilDialog->ExecuteLD(R_MMS_IT_SMIL_DIALOG))
			{
				if(iDocument->SetSMILFilename(filename))
				{
					UpdateContainer();
				}
				else
				{
					HBufC* textResource = StringLoader::LoadLC(R_FILE_NOT_FOUND);
					CAknErrorNote* note = new (ELeave) CAknErrorNote();
					note->ExecuteLD(*textResource);
					CleanupStack::PopAndDestroy(textResource);
				}
			}
			break;
			}
		case ERemoveSubject:
			{
			iDocument->RemoveSubject();
			UpdateContainer();
			break;
			}
		case ESetDefaultSMIL:
			{
			iDocument->RemoveSMILFilename();
			UpdateContainer();
			break;
			}
        default:
            {
            AppUi()->HandleCommandL( aCommand );
            break;
            }
        }
    }

// ---------------------------------------------------------
// CMMS_ItView2::HandleClientRectChange()
// ---------------------------------------------------------
//
void CMMS_ItView2::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CMMS_ItView2::DoActivateL(...)
// ?implementation_description
// ---------------------------------------------------------
//
void CMMS_ItView2::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CMMS_ItContainer2(iUI, iDocument);
        iContainer->SetMopParent(this);
        iContainer->ConstructL( ClientRect() );
        AppUi()->AddToStackL( *this, iContainer );
        }
	iUI->ShowDefaultNaviPaneL();
   }

// ---------------------------------------------------------
// CMMS_ItView2::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CMMS_ItView2::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

void CMMS_ItView2::UpdateContainer()
{
	if(iContainer) iContainer->UpdateLabelsL();
	if(iContainer) iContainer->UpdateEditorL();
}

// End of File

