/*
* ============================================================================
*  Name     : TMMS_ItAttachment from MMS_ItAttachment.h
*  Part of  : MMS_It
*  Created  : 23/10/2004 by Makidis Michael
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Copyright: Makidis Michael 2003-2005
* ============================================================================
*/

// INCLUDE FILES
#include "MMS_ItAttachment.h"

// ================= MEMBER FUNCTIONS =======================

// constructor
TMMS_ItAttachment::TMMS_ItAttachment()
:iMIMETypeSet(EFalse), iSize(0)
    {
    }

// End of File  
